# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: upbaws2025
# "service" is the name of this project. This will also be added to your AWS resource names.
service: serverless-ai-superhero-generator

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1

  httpApi:
    cors:
      allowedOrigins:
        - "*"   # frontend origin
      allowedMethods:
        - "*"
      allowedHeaders:
        - Content-Type
        - Authorization
      allowCredentials: false
  # Uncomment to easily set up a custom domain. Read the docs for more details:
  # https://www.serverless.com/framework/docs/providers/aws/guide/domains
  # domain: api.example.com
  environment:
    UPLOAD_BUCKET: coderoad-aws-community
    PAGE_BUCKET: coderoad-ai-superhero-page
    SAGEMAKER_ENDPOINT: ${ssm:/CODEROAD_SAGEMAKER_ENDPOINT} 
    GOOGLE_API_KEY: ${ssm:/CODEROAD_GOOGLE_API_KEY} # This value comes from AWS System Manager > Parameter Store
    DYNAMO_TABLE: coderoad-dynamodb-aws-community
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - s3:PutObject
            - s3:GetObject
            - s3:ListBucket
          Resource:
            - arn:aws:s3:::${self:provider.environment.UPLOAD_BUCKET}
            - arn:aws:s3:::${self:provider.environment.UPLOAD_BUCKET}/*
        - Effect: "Allow"
          Action:
            - rekognition:RecognizeCelebrities
            - rekognition:CompareFaces
          Resource: "*"
        - Effect: "Allow"
          Action:
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:GetItem
          Resource:
            - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMO_TABLE}
package:
  exclude:
    - node_modules/**
    - .git/**
    - .gitignore
    - README.md
    - .serverless/**
    - package-lock.json
    - nodejs/**
    - public/**
    - client/**
    - layer_content.zip

functions:
  saveProfile:
    handler: src/saveProfile.handler
    layers:
      - { Ref: CoderoadDependenciesLambdaLayer }
    events:
      - httpApi:
          path: /save-profile
          method: POST

  getResultUrl:
    handler: src/getResultUrlV2.handler
    layers:
      - { Ref: CoderoadDependenciesLambdaLayer }
    events:
      - httpApi:
          path: /result-url
          method: POST

  processImage:
    handler: src/processImageV2.handler
    timeout: 300
    layers:
      - { Ref: CoderoadDependenciesLambdaLayer }
    events:
      - s3:
          bucket: ${self:provider.environment.UPLOAD_BUCKET}
          event: s3:ObjectCreated:Put
          existing: true
          rules:
            - prefix: uploads/

layers: 
  coderoadDependencies:
    name: 'coderoad-serverless-dependencies'
    compatibleRuntimes:
      - nodejs20.x
    package:
      artifact: layer_content.zip
resources:
  Resources:
    DynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: ${self:provider.environment.DYNAMO_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    UploadBucket:
      Type: AWS::S3::Bucket
      DeletionPolicy: Retain
      Properties:
        BucketName: ${self:provider.environment.UPLOAD_BUCKET}
        CorsConfiguration:
          CorsRules:
            - AllowedMethods:
                - PUT
                - POST
                - GET
                - DELETE
              AllowedOrigins:
                - "*"
              AllowedHeaders:
                - "*"
              MaxAge: 3000
    
